# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xvW79VsxeX8dPRNiAp2OVeSvqlp5ocMV
"""

import pandas as pd
baza={
    "FISH":[  "G'ofurjonov Shoxrux" , "Abdusalimov Muhammadali" , "Murodjonov Begzod" , "Nematullayeva Afruza" , "Azamova Nargiza"     ],
    "Yoshi":[  "19" , "18" , "19" , "20" , "18"    ],
    "Manzili":[  "Chortoq" , "Farg'ona" , "Beshariq" , "Bog'dod" , "Dang'ara"  ],
    "Jinsi":[   "Erkak" , "Erkak" , "Erkak" , "Ayol" , "Ayol"    ],
    "Ish joyi":[  "TATUF" , "TATUF" , "TATUF" , "FARDU" , "FARDU"  ]

}
db=pd.DataFrame(baza)
print(db)

filtr=db[(db["Ish joyi" ]=="TATUF") & (db["Yoshi" ]>="19")]
print(filtr)

filtr=db[db["Jinsi" ]=="Erkak"]
print(filtr)

filtr=db[db["Ish joyi" ]=="FARDU"]
print(filtr)

filtr=db[db["Manzili" ]=="Dang'ara"]
print(filtr)

filtr=db[db["Yoshi" ]=="19"]
print(filtr)

filtr=db[db["FISH" ]=="Maxsudov Zikrullo"]
print(filtr)